startuppopupversion: 1
gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
keybinding:
    universal:
       prevBlock-alt: 'K' # goto the previous block / panel
       nextBlock-alt: 'J' # goto the next block / panel

