return {
	{ "mcchrish/zenbones.nvim", dependencies = "rktjmp/lush.nvim" },
	"EdenEast/nightfox.nvim",
	"Murtaza-Udaipurwala/gruvqueen",
	"NTBBloodbath/doom-one.nvim",
	"RRethy/nvim-base16",
	"b4skyx/serenade",
	"catppuccin/nvim",
	"ellisonleao/gruvbox.nvim",
	"fenetikm/falcon",
	"folke/tokyonight.nvim",
	"ful1e5/onedark.nvim",
	"jacoborus/tender.vim",
	"maaslalani/nordbuddy",
	"marko-cerovac/material.nvim",
	"mhartington/oceanic-next",
	"rebelot/kanagawa.nvim",
	"rktjmp/lush.nvim",
	"rmehri01/onenord.nvim",
	"rose-pine/neovim",
	"sainnhe/edge",
	"sainnhe/everforest",
	"sainnhe/forest-night",
	"sainnhe/gruvbox-material",
	"sainnhe/sonokai",
	"shaunsingh/nord.nvim",
    "savq/melange-nvim",
    "luisiacc/gruvbox-baby",
    { "AlexvZyl/nordic.nvim"},
    "JoosepAlviste/palenightfall.nvim",
    "ramojus/mellifluous.nvim",
}
